### ISSUE TITLE
RBD_SERVO issue

### ISSUE THREAD

**Issue by MstrLucas** [alextaujenis/RBD_Servo#1]
Hi,
When I trying to upload the demo-sketch  move to degrees to my nano with arduino 1.8.2 I'm getting following error;

exit status 1
Fout bij het compileren van board Arduino Nano (TRANSLATION; Error while compiling board Arduino Nano)

What can be wrong?

**Comment by alextaujenis** [comment]
It appears that you have a syntax error in your code. If you are still having a problem then please re-open this issue and include the Arduino sketch (code) that does not compile.
