### ISSUE TITLE
Is working with board ESp8266?

### ISSUE THREAD

**Issue by imamsan** [alextaujenis/RBD_Servo#2]
I'm get warning below :

_WARNING : library RBD_Servo claims to run on avr architecture(s) and may be incompatible with your current board which runs on esp8266 architecture(s)

Executable segment sizes:
IROM   : 261748          - code in flash         (default or ICACHE_FLASH_ATTR) 
IRAM   : 27704   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 
DATA   : 1252  )         - initialized variables (global, static) in RAM/HEAP 
RODATA : 1888  ) / 81920 - constants             (global, static) in RAM/HEAP 
BSS    : 25544 )         - zeroed variables      (global, static) in RAM/HEAP_

**Comment by alextaujenis** [comment]
All architectures are now supported with the latest release https://github.com/alextaujenis/RBD_Servo/releases/tag/1.0.2
